# On push to main, if the latest version in CHANGELOG.md is different from the latest version tag, create a new tag.

when:
  - event: manual
    branch: main
  - event: push
    branch: main

steps:
  changelog:
    name: Parse Changelog
    image: node:18
    commands:
      - npm ci
      - npm run create-release-env # Saves details to local `.release.env` file

  tag:
    name: Create Tag
    # TODO: Don't do this if the tag already exists
    image: alpine/git
    commands:
      - while read line; do export "$line"; done < .release.env # Created in previous step
      - git tag "v$NEW_RELEASE_VERSION"
      - git push --tags
