# On push to main, if the latest version in CHANGELOG.md is different from the latest version tag, create a new tag.

when:
  - event: manual
    branch: main
  - event: push
    branch: main

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true

steps:
  changelog:
    name: Parse Changelog
    image: node:18
    commands:
      - npm ci
      - npm run create-release-env # Saves details to local `.release.env` file

  tag:
    name: Create Tag
    image: alpine/git
    commands:
      # Prepare env vars, from file created in previous step
      - while read line; do export "$line"; done < .release.env
      - export GIT_CREDENTIALS="$CODEBERG_USERNAME:$CODEBERG_ACCESS_TOKEN"
      - export TAG="v$NEW_RELEASE_VERSION"

      # Tag if not exists
      - if git show-ref --tags $TAG --quiet; then echo tag "$TAG" exists; else git tag "$TAG" && git push https://$GIT_CREDENTIALS@codeberg.org/$CI_REPO.git HEAD:main "$TAG"; fi
    secrets: [codeberg_username, codeberg_access_token]
