# On PR toward `main`: run builds, run tests, and deploy to staging

when:
  - event: manual
  - event: pull_request
    branch: main

steps:
  build_client:
    name: Build Client
    image: node:20
    commands:
      - npm ci
      - npm run build:client
    environment:
      VITE_PUBNUB_SUBSCRIBE_KEY: foo
      VITE_ENABLE_LOGIN:
        from_secret: vite_enable_login
      VITE_ENABLE_SIGNUP:
        from_secret: vite_enable_signup

  build_server:
    name: Build Server
    image: node:20
    commands:
      - cd server
      - npm ci
      - npm run build

  test:
    name: Tests
    depends_on: [Build Client, Build Server]
    image: node:20
    commands:
      - npm test
